services:
  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ssh_shared_orders

    ports:
      - "5432:5432"
    
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: